language: node_js
dist: trusty
sudo: false
node_js:
   - "6"
   - "6.1"
   - "node"
cache:
  directories:
    - node_modules # NPM packages
before_install:
  - if [[ ${TRAVIS_NODE_VERSION} == "node"  ]]; then npm install -g npm@4; fi  # Temporarily workaround issue npm/npm#16824 (regression)
  - wget "http://lorempixel.com/400/200" -O "${TRAVIS_BUILD_DIR}/static/assets/i/test.png"
  - wget "http://lorempixel.com/400/600" -O "${TRAVIS_BUILD_DIR}/static/assets/i/gallery/2016-aoscc-stickers-3.jpg"
addons:
  apt:
    packages:
      - redis-server
script:
  - npm run test
