language: node_js
dist: trusty
sudo: false
node_js:
   - "6"
   - "6.2.2"
   - "node"
cache:
  yarn: true
  directories:
    - node_modules # NPM packages
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH=$HOME/.yarn/bin:$PATH
  - wget "http://lorempixel.com/400/200" -O "${TRAVIS_BUILD_DIR}/static/assets/i/test.png"
  - wget "http://lorempixel.com/400/600" -O "${TRAVIS_BUILD_DIR}/static/assets/i/gallery/2016-aoscc-stickers-3.jpg"
install:
  - yarn
addons:
  apt:
    packages:
      - redis-server
script:
  - yarn test
