language: node_js
dist: trusty
sudo: false
node_js:
   - "6"
   - "6.1"
   - "node"
cache:
  directories:
    - node_modules # NPM packages
    - /tmp/data/
before_install:
  - wget "http://web.archive.org/web/20170317065557/http://www.unicode.org/Public/UNIDATA/UnicodeData.txt" -O /tmp/data/UnicodeData.txt
  - NODE_UNICODETABLE_UNICODEDATA_TXT=/tmp/data/UnicodeData.txt npm update
addons:
  apt:
    packages:
      - redis-server
script:
  - npm run test
