language: node_js
dist: trusty
sudo: false
node_js:
   - "6"
   - "6.1"
   - "node"
before_install:
  - wget "http://web.archive.org/web/20170317065557/http://www.unicode.org/Public/UNIDATA/UnicodeData.txt" -O /tmp/UnicodeData.txt
  - NODE_UNICODETABLE_UNICODEDATA_TXT=/tmp/UnicodeData.txt npm update
  - npm install -g mocha
addons:
  apt:
    packages:
      - redis-server
script:
  - npm run test
